services:
  postgres-user-dev:
    container_name: postgres-user-dev
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      PGDATA: /data/postgres
    volumes:
      - postgres-user-dev:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-dev
    ports:
      - "9411:9411"

  postgres-post-dev:
    container_name: postgres-post-dev
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts
      PGDATA: /data/postgres
    volumes:
      - postgres-post-dev:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  postgres-authentication-dev:
    container_name: postgres-authentication-dev
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication
      PGDATA: /data/postgres
    volumes:
      - postgres-authentication-dev:/data/postgres
    ports:
      - "5436:5432"
    restart: unless-stopped

  postgres-relation-dev:
    container_name: postgres-relation-dev
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: relation
      PGDATA: /data/postgres
    volumes:
      - postgres-relation-dev:/data/postgres
    ports:
      - "5437:5432"

    restart: unless-stopped

  neo4j-relation-dev:
    image: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-relation-data-dev:/data/
    environment:
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/password

  rabbitmq-general-dev:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq-general-dev
    ports:
      - "5672:5672"
      - "15672:15672"

  redis-notification-dev:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-dev:/data

  redis-fee-dev:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-notification-dev:/data


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  postgres-user-dev:
  postgres-post-dev:
  postgres-notification-dev:
  postgres-authentication-dev:
  postgres-relation-dev:
  neo4j-relation-data-dev:
  redis-dev:
    driver: local
  redis-notification-dev:
    driver: local
  elasticsearch-data:
    driver: local