server:
  port: 8120
spring:
  application:
    name: authentication
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5436/authentication
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
