server:
  port: 8080
spring:
  application:
    name: user
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/users
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "confirmation.fb.ripoff@gmail.com"
    password: "D@Dmin2022"
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true