server:
  port: 8085
spring:
  application:
    name: user
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://postgres_user:5432/users?escapeSyntaxCallMode=callIfNoReturn
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "confirmation.fb.ripoff@gmail.com"
    password: "D@Dmin2022"
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: "http://eureka:8761/eureka"
    fetch-registry: true
    register-with-eureka: true