spring:
  application:
    name: relation
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8082