server:
  port: 8090
spring:
  application:
    name: relation
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5437/relation
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
rabbit-queue-definition:
  host: localhost
  port: 5672