server:
  port: 8100
spring:
  application:
    name: notification
  rabbitmq:
    port: 5672
    host: localhost
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true

rabbit-queue-definition:
  host: localhost
  port: 5672

redis:
  url: "localhost"
  port: 6379
