server:
  port: 8100
spring:
  application:
    name: notification
  rabbitmq:
    port: 5672
    host: rabbitmq_general
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://postgres_notification:5432/notifications
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
user-rabbit-queues:
  host: rabbitmq_user_notification
  port: 5672
rabbit-queue-definition:
  host: rabbitmq_general
  port: 5672