server:
  port: 8115
spring:
  application:  
    name: web-server
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
