server:
  port: 8095
spring:
  application:
    name: post
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://postgres_post:5432/posts
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
rabbit-queue-definition:
  host: rabbitmq_general
  port: 5672