server:
  port: 8110
spring:
  application:
    name: feed
  rabbitmq:
    port: 5672
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
