server:
  port: 8110
spring:
  application:
    name: feed
  rabbitmq:
    port: 5672
    host: localhost
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
rabbit-queue-definition:
  host: localhost
  port: 5672
redis:
  url: "localhost"
  port: 6380