server:
  port: 8105
spring:
  application:
    name: mailing
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
mail:
  address: "confirmation.fb.ripoff@gmail.com"
  password: "seyukcfmkgtjgifw"
